# Generated by Django 5.2.3 on 2025-07-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_hackathonconfig_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonconfig',
            name='blockchain_id',
            field=models.IntegerField(blank=True, help_text='ID of this hackathon on the blockchain', null=True),
        ),
    ]
