# Generated by Django 5.2.3 on 2025-07-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_hackathonconfig_blockchain_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hackathonconfig',
            options={'ordering': ['-start_time']},
        ),
        migrations.AddField(
            model_name='hackathonconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
