# Generated by Django 5.2.3 on 2025-07-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_hackathonconfig_blockchain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonconfig',
            name='blockchain_id',
            field=models.IntegerField(blank=True, help_text='ID of this hackathon on the blockchain', null=True, unique=True),
        ),
    ]
