# Generated by Django 5.2.3 on 2025-07-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_alter_hackathonconfig_blockchain_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonconfig',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
