# Generated by Django 5.2.3 on 2025-07-03 09:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='reward_token',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='model',
            field=models.FileField(upload_to='uploads/models/'),
        ),
    ]
