# Generated by Django 5.2.3 on 2025-07-03 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_hackathonconfig_blockchain_id'),
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='hackathon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon.hackathonconfig'),
        ),
    ]
