# Generated by Django 5.2.3 on 2025-07-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='wallet_address',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
