# Generated by Django 5.2.3 on 2025-07-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_aimodel_hackathon'),
        ('model', '0002_aimodel_reward_token_aimodel_uploaded_at_and_more'),
    ]

    operations = [
    ]
