# Generated by Django 5.2.3 on 2025-07-03 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_aimodel_reward_token_aimodel_uploaded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimodel',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='aimodel',
            name='hackathon_id',
            field=models.IntegerField(default=0, help_text='ID of the hackathon this model belongs to'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='aimodel',
            unique_together={('user', 'hackathon_id')},
        ),
    ]
