# Generated by Django 5.2.3 on 2025-07-03 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_alter_aimodel_options_aimodel_hackathon_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimodel',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='aimodel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='hackathon_id',
        ),
    ]
