# Generated by Django 5.2.3 on 2025-07-03 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_hackathonconfig_blockchain_id'),
        ('model', '0003_merge_20250703_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='hackathon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hackathon.hackathonconfig'),
            preserve_default=False,
        ),
    ]
