# Generated by Django 5.2.3 on 2025-07-08 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_hackathonconfig_fulfilled_and_more'),
        ('model', '0004_alter_aimodel_options_alter_aimodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='hackathon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hackathon.hackathonconfig'),
            preserve_default=False,
        ),
    ]
