# Generated by Django 5.2.3 on 2025-07-04 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_alter_aimodel_hackathon'),
        ('model', '0004_alter_aimodel_options_alter_aimodel_unique_together_and_more'),
    ]

    operations = [
    ]
